apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-sample-app
  namespace: staging
  labels:
    app: devops-sample-app
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-sample-app
      environment: staging
  template:
    metadata:
      labels:
        app: devops-sample-app
        environment: staging
    spec:
      containers:
      - name: app
        image: eknathdj/devops-sample-app:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "staging"
        - name: APP_VERSION
          value: "1.0.0"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3