apiVersion: v1
kind: Service
metadata:
  name: devops-sample-app
  namespace: staging
  labels:
    app: devops-sample-app
    environment: staging
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: devops-sample-app
    environment: staging