apiVersion: v1
kind: Service
metadata:
  name: jenkins-metrics
  namespace: default
  labels:
    app: jenkins
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: jenkins
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-monitor
  namespace: default
  labels:
    app: jenkins
    release: prometheus
spec:
  selector:
    matchLabels:
      app: jenkins
  endpoints:
  - port: http
    path: /prometheus
    interval: 30s