apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devops-pipeline-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: devops-pipeline
    interval: 30s
    rules:
    - alert: JenkinsBuildFailure
      expr: increase(jenkins_builds_failed_total[5m]) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Multiple Jenkins build failures"
        description: "More than 2 builds failed in the last 5 minutes"
    
    - alert: ArgocdSyncFailed
      expr: argocd_app_sync_total{phase="Failed"} > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "ArgoCD sync failed"
        description: "Application {{ $labels.name }} failed to sync"
    
    - alert: HighPodRestarts
      expr: rate(kube_pod_container_status_restarts_total{namespace="staging"}[15m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High pod restart rate"
        description: "Pod {{ $labels.pod }} is restarting frequently"
    
    - alert: HighResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High application response time"
        description: "95th percentile response time is above 1 second"
    
    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{namespace="staging"}[1h]) > 5
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.pod }} has restarted more than 5 times in the last hour"