apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  managed-by: argocd
  environment: production