apiVersion: v1
kind: Service
metadata:
  name: devops-sample-app
  namespace: production
  labels:
    app: devops-sample-app
    environment: production
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: devops-sample-app
    environment: production